import type { Metadata } from "next";
import { ArrowLeft, ArrowUpRight, Building2, CalendarDays, Clock3, ExternalLink, FileChartColumn, Globe2, MapPin, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import Link from "next/link";
import { DetailActions } from "@/components/DetailActions";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { formatEventDate, getDurationDays, getEventStatus } from "@/lib/exhibitions/dates";
import { getExhibition } from "@/lib/exhibitions/repository";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const item = await getExhibition((await params).slug); return { title: item?.name ?? "Exhibition", description: item?.tagline }; }

export default async function ExhibitionDetail({ params }: { params: Promise<{ slug: string }> }) {
  const item = await getExhibition((await params).slug); if (!item) notFound();
  const status = getEventStatus(item.startDate, item.endDate); const location = [item.venue, item.address, item.city, item.country].filter(Boolean).join(", ");
  const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location || item.country)}`;
  return <main className="app-page detail-page"><Header /><div className="detail-container"><nav className="breadcrumb"><Link href="/exhibitions"><ArrowLeft /> Exhibitions</Link><span>›</span><Link href={`/exhibitions?industry=${encodeURIComponent(item.industry)}`}>{item.industry}</Link><span>›</span><b>{item.name}</b></nav>
    <section className="detail-hero"><div><h1>{item.name.toUpperCase()}</h1><div className="detail-meta"><span><MapPin />{item.city || item.country}</span><i /><span><CalendarDays />{formatEventDate(item.startDate, item.endDate, true)}</span><i /><Link href={`/exhibitions?industry=${encodeURIComponent(item.industry)}`}>{item.industry.toUpperCase()}</Link></div><DetailActions exhibition={item} /></div><div className="countdown-wrap">{status.state === "upcoming" ? <div className="countdown-cards"><div><CalendarDays /><b>{String(status.days).padStart(2, "0")}</b><small>DAYS</small><em>UNTIL EXHIBITION</em></div><div><Clock3 /><b>{String(status.hours).padStart(2, "0")}</b><small>HOURS</small><em>UNTIL EXHIBITION</em></div><div><Clock3 /><b>{String(status.minutes).padStart(2, "0")}</b><small>MINUTES</small><em>UNTIL EXHIBITION</em></div></div> : <div className={`hero-status ${status.state}`}><b>{status.label.toUpperCase()}</b><span>{status.detail}</span></div>}<div className="detail-cta">{item.website && <a className="button cyan" href={item.website} target="_blank" rel="noopener noreferrer">Visit Official Website <ExternalLink /></a>}<a className="button outline" href={mapsUrl} target="_blank" rel="noopener noreferrer"><MapPin /> Open Location</a></div></div></section>
    <section className="info-strip">{[[CalendarDays, "Category", item.industry], [MapPin, "Location", [item.city, item.country].filter(Boolean).join(", ")], [Building2, "Venue", item.venue || "To be announced"], [CalendarDays, "Date", formatEventDate(item.startDate, item.endDate, true)], [UserRound, "Organizer", item.organizer || "Not specified"]].map(([Icon, label, value]) => { const I = Icon as typeof CalendarDays; return <div key={String(label)}><I /><span><small>{String(label)}</small><b>{String(value)}</b></span></div>; })}</section>
    <section className="detail-content"><div className="report-intel panel"><article className="report"><h2><FileChartColumn /> AI Exhibition Report</h2><p className="cyan-label">Researched by IEC Exhibition Intelligence</p><div className="report-copy">{item.aiReport || item.description || "An intelligence report has not been generated for this exhibition yet."}</div><small>Last updated: {new Date(item.updatedAt).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</small></article><article className="intel"><h2>Exhibition Intelligence</h2>{[["Industry", item.industry], ["Event Type", item.eventType], ["Location", item.country], ["Duration", `${getDurationDays(item.startDate, item.endDate)} Days`]].map(([k, v]) => <div className="intel-row" key={k}><span>{k}</span><b>{v}</b></div>)}<div className="intel-row"><span>Website</span>{item.website ? <a href={item.website} target="_blank" rel="noopener noreferrer">{new URL(item.website).hostname}<ExternalLink /></a> : <b>Not available</b>}</div><h3>Key Topics</h3><div className="tag-row">{item.topics.map((topic) => <Link className="tag" href={`/exhibitions?topic=${encodeURIComponent(topic)}`} key={topic}>{topic}</Link>)}</div></article></div><aside className="map-card panel"><div className="map-visual"><Globe2 /><div className="map-grid" /><span><MapPin /></span><b>{item.venue || item.city || item.country}</b></div><h3>{item.venue || [item.city, item.country].filter(Boolean).join(", ") || "Location unavailable"}</h3><p>{item.address || [item.city, item.country].filter(Boolean).join(", ")}</p><a className="button outline" href={mapsUrl} target="_blank" rel="noopener noreferrer">View on Map <ArrowUpRight /></a></aside></section>
    <section className="sources panel"><div className="sources-title"><Globe2 /><span><h2>Sources & Verification</h2><p>Information verified from multiple trusted sources.</p></span></div>{item.sources.length ? <div className="source-table"><div><b>Source</b><b>URL</b><b>Last Checked</b><b /></div>{item.sources.map((source) => <div key={source.id}><span>{source.label}</span><a href={source.url} target="_blank" rel="noopener noreferrer">{source.url}</a><span>{new Date(source.lastChecked).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</span><a href={source.url} target="_blank" rel="noopener noreferrer" aria-label={`Open ${source.label}`}><ExternalLink /></a></div>)}</div> : <p className="muted">No verification sources have been added.</p>}</section>
  </div><Footer /></main>;
}
