import { BookOpen, ChartNoAxesCombined, CircleCheck, Globe2, Lightbulb, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { Footer } from "./Footer";
import { Header } from "./Header";

const content = {
  reports: { eyebrow: "Market intelligence", title: "Exhibition Reports", intro: "Focused intelligence that turns exhibition data into commercial context.", cards: [[ChartNoAxesCombined, "Market Signals", "Track industries, locations and timing across the global exhibition calendar."], [Globe2, "Global Coverage", "Compare energy-market activity across countries and regions."], [Lightbulb, "Decision Support", "Use verified event context to plan participation and outreach."]] },
  resources: { eyebrow: "Knowledge hub", title: "Resources", intro: "Practical guidance for navigating global energy exhibitions.", cards: [[BookOpen, "Exhibition Guides", "Clear preparation notes for organisers, exhibitors and visitors."], [ShieldCheck, "Source Standards", "How IEC prioritises official and trusted exhibition sources."], [CircleCheck, "Planning Checklists", "Simple tools for evaluating and preparing for an event."]] },
  about: { eyebrow: "International Energy Club", title: "Connecting Energy Markets", intro: "IEC brings trusted exhibition intelligence into one focused, accessible global platform.", cards: [[Globe2, "Global by Design", "A worldwide view of events connecting the energy value chain."], [ShieldCheck, "Verified First", "Official sources and clear provenance sit behind every useful record."], [Lightbulb, "Intelligence, Simplified", "High-quality information without unnecessary workflow complexity."]] },
};

export function ContentPage({ type }: { type: keyof typeof content }) { const page = content[type]; return <main className="app-page"><Header /><section className="simple-hero"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></section><div className="page-container content-space"><div className="feature-grid">{page.cards.map(([Icon, title, copy]) => { const I = Icon as typeof Globe2; return <article className="panel" key={String(title)}><I /><h2>{String(title)}</h2><p>{String(copy)}</p></article>; })}</div>{type === "reports" && <div className="coming-note panel"><span>Report generation is attached to individual exhibition records.</span><Link className="button outline" href="/exhibitions">Browse Intelligence →</Link></div>}{type === "resources" && <section className="legal-grid"><article id="privacy" className="panel"><h2>Privacy</h2><p>IEC ExpoTrack stores exhibition records and saved selections in the configured workspace database. API credentials remain server-side and are never exposed to the browser.</p></article><article id="terms" className="panel"><h2>Terms</h2><p>Exhibition information should be checked against its cited official source before making travel, commercial or contractual decisions.</p></article></section>}</div><Footer /></main>; }
