import type { Exhibition } from "./types";

const base = {
  eventType: "International Exhibition",
  saved: false,
  createdAt: "2026-08-01T09:00:00.000Z",
  updatedAt: "2026-09-12T09:00:00.000Z",
};

function src(id: string, domain: string, label = "Official Exhibition Website") {
  return { id, label, url: `https://${domain}`, lastChecked: "2026-09-12T09:00:00.000Z", priority: 1 };
}

export const seedExhibitions: Exhibition[] = [
  { ...base, id: "gastech-2026", slug: "gastech-2026", name: "Gastech 2026", tagline: "Exhibition & Conference for Natural Gas, LNG and Energy", industry: "Oil & Gas", country: "Singapore", city: "Singapore", venue: "Singapore EXPO", address: "1 Expo Drive, Singapore 486150", startDate: "2026-09-15T09:00:00+08:00", endDate: "2026-09-18T18:00:00+08:00", timezone: "Asia/Singapore", organizer: "DMG Events", website: "https://www.gastechevent.com", description: "Gastech is one of the world’s leading gas and energy exhibitions, bringing together industry leaders, technology providers and decision-makers from across the global energy value chain.", aiReport: "Gastech is one of the world’s leading gas and energy exhibitions, bringing together industry leaders, technology providers and decision-makers from across the global energy value chain. The event focuses on natural gas, LNG, energy transition and low-carbon solutions, making it a key platform for showcasing innovation and building strategic partnerships.", topics: ["Oil & Gas", "Energy", "LNG", "Hydrogen", "Decarbonization"], sources: [src("g1", "www.gastechevent.com"), src("g2", "www.dmgevents.com", "Official Organizer"), src("g3", "singaporeexpo.com.sg", "Official Venue")] },
  { ...base, id: "middle-east-energy-2027", slug: "middle-east-energy-2027", name: "Middle East Energy 2027", tagline: "The region’s leading energy exhibition", industry: "Energy & Power", country: "United Arab Emirates", city: "Dubai", venue: "Dubai World Trade Centre", address: "Sheikh Zayed Road, Dubai", startDate: "2027-04-06T10:00:00+04:00", endDate: "2027-04-08T18:00:00+04:00", timezone: "Asia/Dubai", organizer: "Informa Markets", website: "https://www.middleeast-energy.com", description: "Middle East Energy is the region’s leading exhibition for the energy industry, bringing together global innovators in power generation, renewable energy, transmission and distribution, and energy management.", aiReport: "Middle East Energy connects the complete energy value chain across generation, transmission, distribution and end use. Its Dubai location makes it a major commercial gateway for the Middle East and Africa.", topics: ["Energy & Power", "Renewable Energy", "Oil & Gas", "Transmission", "Utilities"], sources: [src("m1", "www.middleeast-energy.com"), src("m2", "www.informamarkets.com", "Official Organizer"), src("m3", "www.dwtc.com", "Official Venue")] },
  { ...base, id: "hannover-messe-2027", slug: "hannover-messe-2027", name: "Hannover Messe 2027", tagline: "The world’s leading industrial technology show", industry: "Industrial", country: "Germany", city: "Hannover", venue: "Hannover Exhibition Grounds", address: "Messegelände, 30521 Hannover", startDate: "2027-04-19T09:00:00+02:00", endDate: "2027-04-23T18:00:00+02:00", timezone: "Europe/Berlin", organizer: "Deutsche Messe", website: "https://www.hannovermesse.de", description: "A global showcase for industrial transformation, automation and digitalization.", aiReport: "Hannover Messe brings together industrial automation, energy systems, digital ecosystems and engineered parts in one of the world’s most influential B2B platforms.", topics: ["Industrial", "Automation", "Digitalization"], sources: [src("h1", "www.hannovermesse.de")] },
  { ...base, id: "otc-2027", slug: "offshore-technology-conference-2027", name: "Offshore Technology Conference 2027", tagline: "Advancing offshore energy for a stronger future", industry: "Oil & Gas", country: "United States", city: "Houston", venue: "NRG Park", address: "1 NRG Pkwy, Houston, TX", startDate: "2027-05-03T09:00:00-05:00", endDate: "2027-05-06T17:00:00-05:00", timezone: "America/Chicago", organizer: "OTC", website: "https://2027.otcnet.org", description: "A global forum for offshore energy technologies and expertise.", aiReport: "OTC convenes offshore energy professionals to exchange technical knowledge and advance scientific and operational capabilities.", topics: ["Oil & Gas", "Offshore", "Marine"], sources: [src("o1", "2027.otcnet.org")] },
  { ...base, id: "adipec-2026", slug: "adipec-2026", name: "ADIPEC 2026", tagline: "Energy. Intelligence. Impact.", industry: "Oil & Gas", country: "United Arab Emirates", city: "Abu Dhabi", venue: "ADNEC Centre", address: "Khaleej Al Arabi Street, Abu Dhabi", startDate: "2026-11-02T09:00:00+04:00", endDate: "2026-11-05T18:00:00+04:00", timezone: "Asia/Dubai", organizer: "DMG Events", website: "https://www.adipec.com", description: "A global energy gathering focused on practical action and intelligent solutions.", aiReport: "ADIPEC connects ministers, energy leaders, innovators and investors at significant scale.", topics: ["Energy", "Oil & Gas", "Technology"], sources: [src("a1", "www.adipec.com")] },
  { ...base, id: "wind-europe-2027", slug: "wind-europe-2027", name: "WindEurope Annual Event 2027", tagline: "Europe’s wind energy meeting place", industry: "Renewable Energy", country: "Belgium", city: "Brussels", venue: "Brussels Expo", address: "Place de Belgique 1, Brussels", startDate: "2027-04-20T09:00:00+02:00", endDate: "2027-04-22T17:00:00+02:00", timezone: "Europe/Brussels", organizer: "WindEurope", website: "https://windeurope.org", description: "The European wind sector’s flagship conference and exhibition.", aiReport: "WindEurope brings policy, technology and commercial stakeholders together around onshore and offshore wind.", topics: ["Wind", "Renewable Energy", "Offshore"], sources: [src("w1", "windeurope.org")] },
  { ...base, id: "world-hydrogen-week-2026", slug: "world-hydrogen-week-2026", name: "World Hydrogen Week 2026", tagline: "Accelerating the global hydrogen economy", industry: "Hydrogen", country: "Denmark", city: "Copenhagen", venue: "Bella Center", address: "Center Blvd. 5, Copenhagen", startDate: "2026-10-12T09:00:00+02:00", endDate: "2026-10-16T16:00:00+02:00", timezone: "Europe/Copenhagen", organizer: "Sustainable Energy Council", website: "https://www.worldhydrogenweek.com", description: "A focused international meeting for hydrogen leaders and project developers.", aiReport: "The event covers hydrogen production, transport, storage, finance and end use across a full working week.", topics: ["Hydrogen", "Energy Transition", "Net Zero"], sources: [src("hy1", "www.worldhydrogenweek.com")] },
  { ...base, id: "bauma-2025", slug: "bauma-2025", name: "Bauma 2025", tagline: "The world’s leading trade fair for construction machinery", industry: "Construction", country: "Germany", city: "Munich", venue: "Trade Fair Center Messe München", address: "Am Messesee 2, Munich", startDate: "2025-04-07T09:00:00+02:00", endDate: "2025-04-13T18:00:00+02:00", timezone: "Europe/Berlin", organizer: "Messe München", website: "https://bauma.de", description: "The world’s largest trade fair for construction machinery and mining equipment.", aiReport: "Bauma is a benchmark event for heavy equipment, mining and construction innovation.", topics: ["Construction", "Mining", "Equipment"], sources: [src("b1", "bauma.de")] },
  { ...base, id: "solar-storage-live-2027", slug: "solar-storage-live-2027", name: "Solar & Storage Live 2027", tagline: "Powering the energy system of the future", industry: "Renewable Energy", country: "United Kingdom", city: "Birmingham", venue: "NEC Birmingham", address: "Pendigo Way, Birmingham", startDate: "2027-09-21T09:00:00+01:00", endDate: "2027-09-23T17:00:00+01:00", timezone: "Europe/London", organizer: "Terrapinn", website: "https://www.terrapinn.com/exhibition/solar-storage-live", description: "A major gathering for solar, storage and energy technology.", aiReport: "The event spans residential, commercial and utility-scale solar and storage solutions.", topics: ["Solar", "Battery Storage", "Renewable Energy"], sources: [src("s1", "www.terrapinn.com")] },
  { ...base, id: "africa-energy-forum-2027", slug: "africa-energy-forum-2027", name: "Africa Energy Forum 2027", tagline: "Investment and infrastructure for Africa’s energy future", industry: "Energy & Power", country: "South Africa", city: "Cape Town", venue: "CTICC", address: "Convention Square, Cape Town", startDate: "2027-06-15T09:00:00+02:00", endDate: "2027-06-18T17:00:00+02:00", timezone: "Africa/Johannesburg", organizer: "EnergyNet", website: "https://energy-news-network.com", description: "A high-level investment forum for Africa’s energy infrastructure.", aiReport: "AEF connects public and private stakeholders around bankable energy projects across Africa.", topics: ["Investment", "Infrastructure", "Renewable Energy"], sources: [src("af1", "energy-news-network.com")] }
];
